---
- name: PK-Delivery | Install script
  ansible.builtin.copy:
    src: copy-pk.sh
    dest: /usr/local/bin/copy-pk.sh
    owner: root
    group: root
    mode: 0750

- name: PK-Delivery | Check if /root/pks/ exists
  ansible.builtin.stat:
    path: /root/pks
  register: pksdir

- name: PK-Delivery | Create /root/pks if not exists
  ansible.builtin.file:
    path: /root/pks
    state: directory
    mode: 0700
    group: root
    owner: root
  when: pksdir.stat.exists == false

- name: PK-Delivery | Add to /etc/pam.d/sshd
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    line: "session    optional   pam_exec.so /usr/local/bin/copy-pk.sh"
